# -*- coding: utf-8 -*-
"""Set 4 – Formatted Printing and Lists.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rt6BOW4CSZEd3wdrCyUvhL17bga_APs8
"""

#9. Formatted print to screen
x=3.14159
y=2
z=x*y
print(f"Multiplying {x} and {y} gives {z:.3f}")

#12. Square list
num_list = [2, 5, 6, 8, 11]

for num in num_list:
  print(num ** 2)